# Generated by Django 2.0.6 on 2018-07-03 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(db_column='employee_id', max_length=7)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('email_alternate', models.EmailField(max_length=254, null=True, verbose_name='Alternate Email ID')),
                ('mobile_emergency', models.PositiveIntegerField(null=True, verbose_name='Emergency Contact Number')),
                ('address', models.CharField(max_length=250, null=True)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], default='O+', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOfficial',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(max_length=7)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('manager', models.CharField(blank=True, max_length=7, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('cubicle', models.CharField(blank=True, max_length=20, null=True)),
                ('is_current_employee', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('2', 'Two Wheeler'), ('4', 'Four Wheeler')], max_length=1)),
                ('employee_id', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.EmployeeOfficial')),
            ],
        ),
    ]
