# Generated by Django 2.0.6 on 2018-07-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180703_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='employees.Employee'),
        ),
    ]
