# Generated by Django 2.0.6 on 2018-07-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180704_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
