# Generated by Django 2.0.6 on 2018-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180704_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeofficial',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
