# Generated by Django 2.0.6 on 2018-07-31 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20180724_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeofficial',
            old_name='cubicle',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='employeeofficial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='official_data', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
